# Generated by Django 5.0.2 on 2024-03-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='is_read',
            field=models.BooleanField(default=1),
        ),
    ]
